# Project Identification
sonar.projectKey=Hetik1234_StudentManagementSystem
sonar.organization=hetik1234
sonar.host.url=https://sonarcloud.io

# Language & Encoding
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# Source Files
sonar.sources=smsapp,sms_project
sonar.exclusions=**/migrations/**,**/venv/**,**/antenv/**,**/templates/**,manage.py

# Test Files
sonar.tests=smsapp/testsuite
sonar.test.exclusions=**/smsapp/testsuite/**,**/tests/**

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
