sonar.projectKey=Hetik1234_StudentManagementSystem
sonar.organization=hetik1234
sonar.host.url=https://sonarcloud.io
sonar.python.version=3.12
sonar.sources=.
sonar.exclusions=**/migrations/**,**/venv/**,**/antenv/**