name: CI/CD Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build → Scan → Deploy
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for SonarCloud

      # -------------------------
      # SonarCloud Scan
      # -------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
      # -------------------------
      # Python Setup
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------
      # AWS Credentials
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # -------------------------
      # Docker Build → ECR Push
      # -------------------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin 628743843080.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t sms_project_web .

      - name: Tag Docker image
        run: docker tag sms_project_web:latest 628743843080.dkr.ecr.us-east-1.amazonaws.com/student_management_system:latest

      - name: Push Docker image
        run: docker push 628743843080.dkr.ecr.us-east-1.amazonaws.com/student_management_system:latest

      # -------------------------
      # EB ZIP packaging
      # -------------------------
      - name: Create EB package
        run: zip -r deploy.zip Dockerrun.aws.json .elasticbeanstalk/

      # -------------------------
      # Deploy to Elastic Beanstalk
      # -------------------------
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          application_name: StudentManagementSystem
          environment_name: sms-env
          region: us-east-1
          version_label: v-${{ github.run_number }}
          deployment_package: deploy.zip
